image: debian/bullseye
packages:
  - buildah
  - crun
sources:
  - https://git.sr.ht/~adamcstephens/iguanair-docker
environment:
  project: iguanair-docker
  image_tag: quay.io/adamctephens/iguanair-docker:latest
secrets:
  - 7c673008-721a-485e-b234-11205da4fa0b
tasks:
  # - skip_if_not_release: |
  #     cd $project
  #     git describe --exact-match HEAD || complete-build
  - build: |
      cd $project
      buildah login -u adamctephens+srht  --password-stdin < ~/.password quay.io

      if [[ "$(uname -m)" == "x86_64" ]]; then
        S6_ARCH=amd64
        DEB_ARCH=amd64
      elif [[ "$(uname -m)" == "x86_64" ]]; then
        S6_ARCH=aarch64
        DEB_ARCH=arm64
      else
        echo "unsupported arch"
        exit 1
      fi

      set -x
      buildah bud -f Dockerfile --tag $image_tag --target final --build-arg S6_ARCH=$S6_ARCH --build-arg DEB_ARCH=$DEB_ARCH .
      buildah push $image_tag
