version: "3.5"

services:
  lirc:
    image: quay.io/adamcstephens/iguanair
    privileged: true
    restart: unless-stopped
    volumes:
      - /dev/bus/usb:/dev/bus/usb
  api:
    command: -s lirc:8765
    image: ghcr.io/adamcstephens/lirc-web-api
    ports:
      - 3000:3000
    restart: unless-stopped
