version: "3.5"

services:
  lirc:
    image: local/iguanair
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
  api:
    command: -s lirc:8765
    image: ghcr.io/adamcstephens/lirc-web-api
    ports:
      - 3000:3000
