version: "3.5"

services:
  lirc:
    image: localhost/iguanair-docker:latest
    privileged: true
    restart: unless-stopped
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./lirc/lircd.conf.d:/etc/lirc/lircd.conf.d
  api:
    command: -s lirc:8765
    image: ghcr.io/adamcstephens/lirc-web-api
    ports:
      - 3000:3000
    restart: unless-stopped
